CREATE TABLE FEATURE_LIST_REGISTRY (
  NAME VARCHAR,
  VERSION VARCHAR,
  DESCRIPTION VARCHAR,
  READINESS VARCHAR DEFAULT 'DRAFT',
  STATUS VARCHAR DEFAULT 'DRAFT',
  FEATURE_VERSIONS VARIANT,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
