CREATE TABLE ONLINE_STORE_MAPPING (
  TILE_ID VARCHAR,
  AGGREGATION_ID VARCHAR,
  RESULT_ID VARCHAR,
  RESULT_TYPE VARCHAR,
  SQL_QUERY VARCHAR,
  ONLINE_STORE_TABLE_NAME VARCHAR,
  ENTITY_COLUMN_NAMES VARCHAR,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
