CREATE TABLE TILE_FEATURE_MAPPING (
  TILE_ID VARCHAR,
  FEATURE_NAME VARCHAR,
  FEATURE_VERSION VARCHAR,
  FEATURE_SQL VARCHAR,
  FEATRUE_STORE_TABLE_NAME VARCHAR,

  FEATURE_ENTITY_COLUMN_NAMES VARCHAR,

  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
