"""
Test target module
"""
import pytest

from tests.unit.api.base_feature_or_target_test import FeatureOrTargetBaseTestSuite, TestItemType


class TestTargetTestSuite(FeatureOrTargetBaseTestSuite):
    """Test suite for target"""

    item_type = TestItemType.TARGET
    expected_item_definition = """
    # Generated by SDK version: 0.3.0
    from bson import ObjectId
    from featurebyte import EventTable

    event_table = EventTable.get_by_id(ObjectId("{table_id}"))
    event_view = event_table.get_view(
        view_mode="manual",
        drop_column_names=["created_at"],
        column_cleaning_operations=[],
    )
    target = event_view.groupby(
        by_keys=["cust_id"], category=None
    ).forward_aggregate(
        value_column="col_float",
        method="sum",
        window="1d",
        target_name="float_target",
    )
    feat = target["float_target"]
    output = feat
    """
    expected_saved_item_definition = """
    # Generated by SDK version: 0.3.0
    from bson import ObjectId
    from featurebyte import EventTable


    # event_table name: "sf_event_table"
    event_table = EventTable.get_by_id(ObjectId("{table_id}"))
    event_view = event_table.get_view(
        view_mode="manual",
        drop_column_names=["created_at"],
        column_cleaning_operations=[],
    )
    target = event_view.groupby(
        by_keys=["cust_id"], category=None
    ).forward_aggregate(
        value_column="col_float",
        method="sum",
        window="1d",
        target_name="float_target",
    )
    feat = target["float_target"]
    output = feat
    output.save(_id=ObjectId("{item_id}"))
    """

    def test_invalid_operations_with_feature(self, bool_feature, float_target, float_feature):
        """
        Test invalid operations with feature
        """
        # Test binary series operation
        with pytest.raises(TypeError) as exc_info:
            _ = float_target + float_feature
        assert "Operation between Target and Feature is not supported" in str(exc_info)

        # Test series assignment
        with pytest.raises(TypeError) as exc_info:
            float_target[bool_feature] = float_feature
        assert "Operation between Target and Feature is not supported" in str(exc_info)
