"""
Constants
"""
import inspect

EMPTY_VALUE = inspect._empty

ACTIVATE = "Activate"
ADD_METADATA = "Add Metadata"
CATALOG = "Catalog"
CLEANING_OPERATION = "Cleaning Operation"
CONSTRUCTOR = "Cosntructor"
CREATE = "Create"
CREATE_FEATURE = "Create Feature"
CREATE_FEATURE_GROUP = "Create Feature Group"
CREATE_TABLE = "Create Table"
CLASS_METHODS = "Class Methods"
DATA_SOURCE = "DataSource"
DEPLOY = "Deploy"
ENTITY = "Entity"
ENUMS = "Enums"
EXPLORE = "Explore"
FEATURE = "Feature"
FEATURE_GROUP = "FeatureGroup"
FEATURE_JOB = "Feature Job"
FEATURE_JOB_SETTING = "Feature Job Setting"
FEATURE_LIST = "FeatureList"
FEATURE_STORE = "FeatureStore"
GET = "Get"
GET_VIEW = "Get View"
GROUPBY = "Groupby"
IMPUTATION = "Imputation"
INFO = "Info"
JOIN = "Join"
LAGS = "Lags"
LINEAGE = "Lineage"
LIST = "List"
MANAGE = "Manage"
RELATIONSHIP = "Relationship"
SAVE = "Save"
SERVE = "Serve"
SET_FEATURE_JOB = "Set Feature Job"
SOURCE_TABLE = "SourceTable"
TABLE = "Table"
TABLE_COLUMN = "TableColumn"
TRANSFORM = "Transform"
TYPE = "Type"
UTILITY_CLASSES = "Utility Classes"
VERSION = "Version"
VIEW = "View"
VIEW_COLUMN = "ViewColumn"
WAREHOUSE = "Warehouse"
