"""
Constants
"""
import inspect

EMPTY_VALUE = inspect._empty

ACTIVATE = "Activate"
ADD_METADATA = "Add Metadata"
CATALOG = "Catalog"
CREATE = "Create"
DATA_SOURCE = "DataSource"
ENTITY = "Entity"
ENUMS = "Enums"
EXPLORE = "Explore"
FEATURE = "Feature"
FEATURE_GROUP = "FeatureGroup"
FEATURE_JOB = "Feature Job"
FEATURE_LIST = "FeatureList"
FEATURE_STORE = "FeatureStore"
GET = "Get"
IMPUTATION = "Imputation"
INFO = "Info"
JOIN = "Join"
LAGS = "Lags"
LINEAGE = "Lineage"
LIST = "List"
RELATIONSHIP = "Relationship"
SERVE = "Serve"
SOURCE_TABLE = "SourceTable"
TABLE = "Table"
TABLE_COLUMN = "TableColumn"
TRANSFORM = "Transform"
TYPE = "Type"
UPDATE = "Update"
UTILITY_CLASSES = "Utility Classes"
VERSION = "Version"
VIEW = "View"
VIEW_COLUMN = "ViewColumn"
