"""
Constants
"""

import inspect

EMPTY_VALUE = inspect._empty

ACTIVATE = "Activate"
ADD_METADATA = "Add Metadata"
BATCH_FEATURE_TABLE = "BatchFeatureTable"
BATCH_REQUEST_TABLE = "BatchRequestTable"
CATALOG = "Catalog"
CLEANING_OPERATION = "Cleaning Operation"
CONSTRUCTOR = "Constructor"
CONTEXT = "Context"
CREATE = "Create"
CREATE_FEATURE = "Create Feature"
CREATE_FEATURE_GROUP = "Create Feature Group"
CREATE_TABLE = "Create Table"
CREATE_TARGET = "Create Target"
CREDENTIAL = "Credential"
CLASS_METHODS = "Class Methods"
DATA_SOURCE = "DataSource"
DEPLOY = "Deploy"
DEPLOYMENT = "Deployment"
ENTITY = "Entity"
ENUMS = "Enums"
EXPLORE = "Explore"
FEATURE = "Feature"
FEATURE_GROUP = "FeatureGroup"
FEATURE_JOB_SETTING = "Feature Job Setting"
FEATURE_LIST = "FeatureList"
FEATURE_STORE = "FeatureStore"
GET = "Get"
GET_VIEW = "Get View"
GROUPBY = "Groupby"
HISTORICAL_FEATURE_TABLE = "HistoricalFeatureTable"
IMPUTATION = "Imputation"
INFO = "Info"
JOIN = "Join"
LAGS = "Lags"
LINEAGE = "Lineage"
LIST = "List"
MANAGE = "Manage"
OBSERVATION_TABLE = "ObservationTable"
ONLINE_STORE = "OnlineStore"
ONLINE_STORE_DETAILS = "Online Store Details"
RELATIONSHIP = "Relationship"
REQUEST_COLUMN = "RequestColumn"
SAVE = "Save"
SERVE = "Serve"
SET_FEATURE_JOB = "Set Feature Job"
SOURCE_TABLE = "SourceTable"
TABLE = "Table"
TABLE_COLUMN = "TableColumn"
TARGET = "Target"
TARGET_NAMESPACE = "TargetNamespace"
TRANSFORM = "Transform"
TYPE = "Type"
USE_CASE = "UseCase"
USER_DEFINED_FUNCTION = "UserDefinedFunction"
UTILITY_CLASSES = "Utility Classes"
UTILITY_METHODS = "Utility Methods"
VERSION = "Version"
VIEW = "View"
VIEW_COLUMN = "ViewColumn"
WAREHOUSE = "Feature Store Details"
