"""
Test source types
"""

SNOWFLAKE = "snowflake"
SPARK = "spark"
DATABRICKS = "databricks"
DATABRICKS_UNITY = "databricks_unity"

SNOWFLAKE_AND_SPARK = [SNOWFLAKE, SPARK]
SNOWFLAKE_SPARK_DATABRICKS = [SNOWFLAKE, SPARK, DATABRICKS]
SNOWFLAKE_SPARK_DATABRICKS_UNITY = [SNOWFLAKE, SPARK, DATABRICKS_UNITY]
SNOWFLAKE_SPARK_DATABRICKS_AND_UNITY = [SNOWFLAKE, SPARK, DATABRICKS, DATABRICKS_UNITY]
