CREATE OR REPLACE TABLE FEATURE_REGISTRY (
  ID INT AUTOINCREMENT,

  NAME VARCHAR,
  STATUS VARCHAR DEFAULT 'DRAFT',
  ENTITY_COLUMNS VARCHAR,
  TIMESTAMP_COLUMN VARCHAR,
  AGGREGATE_FUNC VARCHAR,

  FREQUENCY_MINUTES INT,
  TIME_MODULO_FREQUENCY_SECOND INT,
  BLIND_SPOT_SECOND INT,
  TILE_SQL VARCHAR,
  COLUMN_NAMES VARCHAR,
  TILE_ID VARCHAR,
  ONLINE_ENABLED VARCHAR(1) DEFAULT 'N',

  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
