CREATE OR REPLACE TABLE FEATURE_LIST_REGISTRY (
  NAME VARCHAR,
  VERSION VARCHAR,
  IS_DEFAULT BOOLEAN DEFAULT True,
  STATUS VARCHAR DEFAULT 'DRAFT',
  FEATURE_VERSIONS VARIANT,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
