CREATE OR REPLACE TABLE FEATURE_LIST_REGISTRY (
  ID INT AUTOINCREMENT,

  NAME VARCHAR,
  VERSION VARCHAR,
  IS_DEFAULT BOOLEAN DEFAULT True,
  STATUS VARCHAR DEFAULT 'DRAFT',

  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
