CREATE TABLE TILE_REGISTRY (
  TILE_ID VARCHAR,
  TILE_SQL VARCHAR,
  ENABLED BOOLEAN DEFAULT True,
  LAST_TILE_INDEX_ONLINE INT DEFAULT -1,
  LAST_TILE_INDEX_OFFLINE INT DEFAULT -1,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
