CREATE OR REPLACE TABLE TILE_REGISTRY (
  ID INT AUTOINCREMENT,
  TILE_ID VARCHAR,
  TILE_SQL VARCHAR,
  ENABLED VARCHAR(1) DEFAULT 'Y',
  LAST_TILE_INDEX_ONLINE INT DEFAULT -1,
  LAST_TILE_INDEX_OFFLINE INT DEFAULT -1,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE()
);
