version: "3.8"

services:
  featurebyte-server:
    hostname: featurebyte-server
    container_name: featurebyte-server
    image: featurebyte-beta:latest
    volumes:
      - ~/.featurebyte:/app/.featurebyte
      - /tmp:/tmp
    environment:
      FEATUREBYTE_HOME: /app/.featurebyte
    ports:
      - "127.0.0.1:8090:8090"  # jupyter-notebook
