CREATE OR REPLACE FUNCTION F_COUNT_DICT_MOST_FREQUENT_VALUE(counts MAP<STRING, INT>)
  RETURNS DOUBLE
  LANGUAGE SQL
    return CAST(F_COUNT_DICT_MOST_FREQUENT_KEY_VALUE(counts, FALSE).most_frequent_count AS DOUBLE);
