CREATE TABLE IF NOT EXISTS TILE_REGISTRY (
  TILE_ID STRING,
  AGGREGATION_ID STRING,
  TILE_SQL STRING,
  ENTITY_COLUMN_NAMES STRING,
  VALUE_COLUMN_NAMES STRING,
  VALUE_COLUMN_TYPES STRING,
  FREQUENCY_MINUTE INT,
  TIME_MODULO_FREQUENCY_SECOND INT,
  BLIND_SPOT_SECOND INT,
  IS_ENABLED BOOLEAN,

  LAST_TILE_START_DATE_ONLINE TIMESTAMP,
  LAST_TILE_INDEX_ONLINE INT,

  LAST_TILE_START_DATE_OFFLINE TIMESTAMP,
  LAST_TILE_INDEX_OFFLINE INT,

  CREATED_AT TIMESTAMP
) USING DELTA PARTITIONED BY (TILE_ID, ENTITY_COLUMN_NAMES);
