# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import CalendarTable

calendar_table = CalendarTable.get_by_id(ObjectId("{table_id}"))
calendar_view = calendar_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
output = calendar_view
