# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import CastToNumeric
from featurebyte import ColumnCleaningOperation
from featurebyte import EventTable

event_table = EventTable.get_by_id(ObjectId("{table_id}"))
event_view = event_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="col_text",
            cleaning_operations=[CastToNumeric(target_dtype="FLOAT")],
        )
    ],
)
grouped = event_view.as_features(
    column_names=["col_text"], feature_names=["latest_col_text"], offset=None
)
feat = grouped["latest_col_text"]
output = feat
