# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import CastToNumeric
from featurebyte import ColumnCleaningOperation
from featurebyte import EventTable
from featurebyte import FeatureJobSetting

event_table = EventTable.get_by_id(ObjectId("{table_id}"))
event_view = event_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="col_text",
            cleaning_operations=[CastToNumeric(target_dtype="INT")],
        )
    ],
)
grouped = event_view.groupby(by_keys=["cust_id"], category=None).aggregate_over(
    value_column="col_text",
    method="sum",
    windows=["7d"],
    feature_names=["sum_col_text_7d"],
    feature_job_setting=FeatureJobSetting(
        blind_spot="90s", period="900s", offset="180s"
    ),
    skip_fill_na=True,
    offset=None,
)
feat = grouped["sum_col_text_7d"]
output = feat
