# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import ColumnCleaningOperation
from featurebyte import MissingValueImputation
from featurebyte import SCDTable

scd_table = SCDTable.get_by_id(ObjectId("{table_id}"))
change_view = scd_table.get_change_view(
    track_changes_column="col_int",
    default_feature_job_setting=None,
    prefixes=None,
    view_mode="manual",
    drop_column_names=[],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="col_int", cleaning_operations=[MissingValueImputation(imputed_value=0)]
        )
    ],
)
output = change_view
