# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import ChangeView
from featurebyte import ColumnCleaningOperation
from featurebyte import MissingValueImputation
from featurebyte import SlowlyChangingData

scd_data = SlowlyChangingData.get_by_id(ObjectId("{data_id}"))
change_view = ChangeView.from_slowly_changing_data(
    slowly_changing_data=scd_data,
    track_changes_column="col_int",
    default_feature_job_setting=None,
    prefixes=None,
    view_mode="manual",
    drop_column_names=[],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="col_int", cleaning_operations=[MissingValueImputation(imputed_value=0)]
        )
    ],
)
output = change_view
