# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import EventTable

event_table = EventTable.get_by_id(ObjectId("{data_id}"))
event_view = event_table.get_view(
    view_mode="manual", drop_column_names=["created_at"], column_cleaning_operations=[]
)
col = event_view["col_int"]
col_1 = (((col > 1) & (col < 10)) | (col == 1)) | (col != 10)
output = (col_1 | (col >= 1)) | (col <= 10)
