# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import EventData
from featurebyte import EventView

event_data = EventData.get_by_id(ObjectId("{data_id}"))
event_view = EventView.from_event_data(
    event_data=event_data,
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
col = event_view["col_text"]
col_1 = col.str.len().astype(str) + col.str.strip(to_strip=" ")
col_2 = col_1 + col.str.replace(pat=" ", repl="_")
col_3 = col_2 + col.str.pad(width=10, side="left", fillchar="_")
col_4 = (col_3 + col.str.upper()) + col.str.lower()
col_5 = col_4 + col.str.contains(pat=" ", case=True).astype(str)
output = col_5 + col.str.slice(start=0, stop=10)
