# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import EventData

event_data = EventData.get_by_id(ObjectId("{data_id}"))
event_view = event_data.get_view(
    view_mode="manual", drop_column_names=["created_at"], column_cleaning_operations=[]
)
col = event_view["col_float"]
col_1 = event_view["col_int"]
col_2 = (col_1 > 10).astype(int) - (~(col_1 > 10)).astype(int)
col_3 = (col_1.floor() * col.log()) / col_1.exp()
col_4 = (col_2 - col.abs().sqrt().ceil()) + col_3
output = col_4 + col_1.isnull().astype(float)
