# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import EventData
from featurebyte import EventView

event_data = EventData.get_by_id(ObjectId("{data_id}"))
event_view = EventView.from_event_data(event_data=event_data)
col = (event_view["col_int"] > 1) & (event_view["col_int"] < 10)
col_1 = (col | (event_view["col_int"] == 1)) | (event_view["col_int"] != 10)
col_2 = (col_1 | (event_view["col_int"] >= 1)) | (event_view["col_int"] <= 10)
output = col_2
