# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import EventData
from featurebyte import EventView

event_data = EventData.get_by_id(ObjectId("{data_id}"))
event_view = EventView.from_event_data(event_data=event_data)
col = (~(event_view["col_int"] > 10)).astype(int)
col_1 = ((event_view["col_int"] > 10).astype(int)) - col
col_2 = ((event_view["col_float"].abs()).sqrt()).ceil()
col_3 = (event_view["col_int"].floor()) * (event_view["col_float"].log())
col_4 = (col_1 - col_2) + (col_3 / (event_view["col_int"].exp()))
col_5 = (event_view["col_int"].isnull()).astype(float)
output = col_4 + col_5
