# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import EventData
from featurebyte import EventView

event_data = EventData.get_by_id(ObjectId("{data_id}"))
event_view = EventView.from_event_data(event_data=event_data)
col = event_view["col_int"]
col_1 = event_view["col_float"]
col_2 = ((1 - col) * (col_1 - 1)) / (col + col_1)
col_3 = (col_2 + (1 / (col - col_1))) + (col % 10)
output = (col_3 - (col_1.pow(2))) + col
