# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import DimensionTable

dimension_table = DimensionTable.get_by_id(ObjectId("{data_id}"))
dimension_view = dimension_table.get_view(
    view_mode="manual", drop_column_names=["created_at"], column_cleaning_operations=[]
)
output = dimension_view
