# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import ColumnCleaningOperation
from featurebyte import DisguisedValueImputation
from featurebyte import EventTable
from featurebyte import MissingValueImputation

event_table = EventTable.get_by_id(ObjectId("{table_id}"))
event_view = event_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="col_int",
            cleaning_operations=[MissingValueImputation(imputed_value=-1)],
        ),
        ColumnCleaningOperation(
            column_name="col_float",
            cleaning_operations=[
                DisguisedValueImputation(
                    imputed_value=-1, disguised_values=[-99]
                )
            ],
        ),
    ],
)
output = event_view
