# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import DimensionTable
from featurebyte import EventTable

dimension_table = DimensionTable.get_by_id(ObjectId("6337f9651050ee7d1234660d"))
dimension_view = dimension_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
view = dimension_view[["col_int", "col_text"]]
event_table = EventTable.get_by_id(ObjectId("{table_id}"))
event_view = event_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
joined_view = event_view.join(view, on=None, how="left", rsuffix="")
col = joined_view["event_timestamp"]
col_1 = joined_view["tz_offset"]
joined_view["event_timestamp_hour"] = col.dt.tz(col_1).hour
output = joined_view
