# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import SCDTable

scd_table = SCDTable.get_by_id(ObjectId("{table_id}"))
scd_view = scd_table.get_view(
    view_mode="manual",
    drop_column_names=["is_active"],
    column_cleaning_operations=[],
)
scd_view["os_type"] = "unknown"
col = scd_view["os_type"]
col_1 = ~col.str.contains(pat="window", case=True)
col_2 = col_1 & (~col.str.contains(pat="mac", case=True))
col_3 = col + "_new"
col_3[col_2] = "other"
view = scd_view.copy()
view["other_os_type"] = col_3
grouped = view.as_features(
    column_names=["other_os_type"], feature_names=["other_os_type"], offset=None
)
feat = grouped["other_os_type"]
output = feat
