# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import ColumnCleaningOperation
from featurebyte import ItemData
from featurebyte import MissingValueImputation

item_data = ItemData.get_by_id(ObjectId("{data_id}"))
item_view = item_data.get_view(
    event_suffix="_event_data",
    view_mode="manual",
    drop_column_names=[],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="item_amount", cleaning_operations=[MissingValueImputation(imputed_value=0)]
        )
    ],
    event_drop_column_names=["created_at"],
    event_column_cleaning_operations=[],
    event_join_column_names=["event_timestamp", "cust_id"],
)
grouped = item_view.as_features(
    column_names=["item_amount"], feature_names=["ItemAmountFeature"], offset=None
)
feat = grouped["ItemAmountFeature"]
output = feat
