# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import ColumnCleaningOperation
from featurebyte import ItemTable
from featurebyte import MissingValueImputation

item_table = ItemTable.get_by_id(ObjectId("{table_id}"))
item_view = item_table.get_view(
    event_suffix="_event_table",
    view_mode="manual",
    drop_column_names=[],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="event_id_col",
            cleaning_operations=[MissingValueImputation(imputed_value=-999)],
        )
    ],
    event_drop_column_names=["created_at"],
    event_column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="col_int", cleaning_operations=[MissingValueImputation(imputed_value=-99)]
        )
    ],
    event_join_column_names=["event_timestamp", "cust_id"],
)
feat = item_view.groupby(by_keys=["event_id_col"], category=None).aggregate(
    value_column="cust_id_event_table", method="sum", feature_name="order_size", skip_fill_na=True
)
feat_1 = feat + 123
feat_1.name = "feat"
output = feat_1
