# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import EventTable
from featurebyte.api.request_column import RequestColumn

event_table = EventTable.get_by_id(ObjectId("{table_id}"))
event_view = event_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
grouped = event_view.groupby(by_keys=["cust_id"], category=None).aggregate_over(
    value_column="event_timestamp",
    method="latest",
    windows=["90d"],
    feature_names=["latest_event_timestamp_90d"],
    feature_job_setting={{
        "blind_spot": "3600s",
        "frequency": "3600s",
        "time_modulo_frequency": "1800s",
    }},
    skip_fill_na=True,
)
feat = grouped["latest_event_timestamp_90d"]
feat_1 = RequestColumn.create_request_column("POINT_IN_TIME", "TIMESTAMP")
feat_2 = (feat_1 - feat).dt.day
feat_2.name = "Time Since Last Event (days)"
output = feat_2
