# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import ForecastTable

forecast_table = ForecastTable.get_by_id(ObjectId("{table_id}"))
forecast_view = forecast_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
output = forecast_view
