# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import SCDTable

scd_table = SCDTable.get_by_id(ObjectId("{table_id}"))
scd_view = scd_table.get_view(
    view_mode="manual",
    drop_column_names=["is_active"],
    column_cleaning_operations=[],
)
target = scd_view.groupby(
    by_keys=["col_boolean"], category=None
).forward_aggregate_asat(
    value_column="col_float",
    method="sum",
    target_name="asat_target",
    offset=None,
    fill_value=None,
    skip_fill_na=True,
)
target_1 = target.copy()
target_1[target.isnull()] = 0.0
target_1.name = "asat_target"
output = target_1
