# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import EventData
from featurebyte import EventView
from featurebyte import ItemData
from featurebyte import ItemView

event_data = EventData.get_by_id(ObjectId("{event_data_id}"))
event_view = EventView.from_event_data(event_data=event_data)
item_data = ItemData.get_by_id(ObjectId("{data_id}"))
item_view = ItemView.from_item_data(item_data=item_data, event_suffix="_event_data")
output = item_view
