# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import ColumnCleaningOperation
from featurebyte import ItemTable
from featurebyte import MissingValueImputation
from featurebyte import StringValueImputation
from featurebyte import UnexpectedValueImputation
from featurebyte import ValueBeyondEndpointImputation

item_table = ItemTable.get_by_id(ObjectId("{table_id}"))
item_view = item_table.get_view(
    event_suffix="_event_table",
    view_mode="manual",
    drop_column_names=[],
    column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="item_amount",
            cleaning_operations=[
                ValueBeyondEndpointImputation(type="less_than", end_point=0, imputed_value=0),
                StringValueImputation(imputed_value=0),
            ],
        )
    ],
    event_drop_column_names=[],
    event_column_cleaning_operations=[
        ColumnCleaningOperation(
            column_name="col_int", cleaning_operations=[MissingValueImputation(imputed_value=0)]
        ),
        ColumnCleaningOperation(
            column_name="col_char",
            cleaning_operations=[
                UnexpectedValueImputation(
                    imputed_value="unknown", expected_values=["a", "b", "c", "unknown"]
                )
            ],
        ),
    ],
    event_join_column_names=["event_timestamp"],
)
output = item_view
