# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import FeatureStore
from featurebyte import ItemData
from featurebyte import SnowflakeDetails
from featurebyte.query_graph.model.column_info import ColumnInfo
from featurebyte.query_graph.model.common_table import TabularSource
from featurebyte.query_graph.node.schema import TableDetails

item_data = ItemData(
    name="item_data",
    feature_store=FeatureStore(
        name="sf_featurestore",
        type="snowflake",
        details=SnowflakeDetails(
            account="sf_account",
            warehouse="sf_warehouse",
            database="sf_database",
            sf_schema="sf_schema",
        ),
    ),
    tabular_source=TabularSource(
        feature_store_id=ObjectId("{feature_store_id}"),
        table_details=TableDetails(
            database_name="sf_database", schema_name="sf_schema", table_name="items_table"
        ),
    ),
    columns_info=[
        ColumnInfo(name="event_id_col", dtype="INT"),
        ColumnInfo(name="item_id_col", dtype="VARCHAR"),
        ColumnInfo(name="item_type", dtype="VARCHAR"),
        ColumnInfo(name="item_amount", dtype="FLOAT"),
        ColumnInfo(name="created_at", dtype="TIMESTAMP_TZ"),
        ColumnInfo(name="event_timestamp", dtype="TIMESTAMP_TZ"),
    ],
    record_creation_date_column=None,
    item_id_column="item_id_col",
    event_id_column="event_id_col",
    event_data_id=ObjectId("{event_data_id}"),
    _id=ObjectId("{data_id}"),
)
output = item_data
