# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import DimensionTable

dimension_table = DimensionTable.get_by_id(ObjectId("{table_id}"))
output = dimension_table
