# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import TimeSeriesTable

time_series_table = TimeSeriesTable.get_by_id(
    ObjectId("{table_id}")
)
output = time_series_table
