# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import SnapshotsTable

snapshots_table = SnapshotsTable.get_by_id(ObjectId("{table_id}"))
output = snapshots_table
