# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import SlowlyChangingData

slowly_changing_data = SlowlyChangingData.get_by_id(ObjectId("{data_id}"))
scd_view = slowly_changing_data.get_view(
    view_mode="manual", drop_column_names=[], column_cleaning_operations=[]
)
output = scd_view
