# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import SCDTable

scd_table = SCDTable.get_by_id(ObjectId("{table_id}"))
scd_view = scd_table.get_view(
    view_mode="manual", drop_column_names=[], column_cleaning_operations=[]
)
output = scd_view
