# Generated by SDK version: 0.1.0
from bson import ObjectId
from featurebyte import SlowlyChangingData
from featurebyte import SlowlyChangingView

scd_data = SlowlyChangingData.get_by_id(ObjectId("{data_id}"))
scd_view = SlowlyChangingView.from_slowly_changing_data(slowly_changing_data=scd_data)
output = scd_view
