# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import SnapshotsTable

snapshots_table = SnapshotsTable.get_by_id(ObjectId("{table_id}"))
snapshots_view = snapshots_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
output = snapshots_view
