# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import SCDTable

scd_table = SCDTable.get_by_id(ObjectId("{table_id}"))
scd_view = scd_table.get_view(
    view_mode="manual",
    drop_column_names=["is_active"],
    column_cleaning_operations=[],
)
col = scd_view["col_float"]
view = scd_view.copy()
view['"quote column"'] = col * 2
target = view['"quote column"'].as_target(
    target_name="Target name with special characters",
    offset=None,
    fill_value=None,
)
output = target
