# Generated by SDK version: {sdk_version}
from bson import ObjectId
from featurebyte import TimeSeriesTable

time_series_table = TimeSeriesTable.get_by_id(
    ObjectId("{table_id}")
)
time_series_view = time_series_table.get_view(
    view_mode="manual",
    drop_column_names=["created_at"],
    column_cleaning_operations=[],
)
output = time_series_view
