CREATE TABLE IF NOT EXISTS ONLINE_STORE_MAPPING (
  TILE_ID STRING,
  AGGREGATION_ID STRING,
  RESULT_ID STRING,
  RESULT_TYPE STRING,
  SQL_QUERY STRING,
  ONLINE_STORE_TABLE_NAME STRING,
  ENTITY_COLUMN_NAMES STRING,
  IS_DELETED BOOLEAN,
  CREATED_AT TIMESTAMP
) USING DELTA PARTITIONED BY (TILE_ID);
