CREATE TABLE IF NOT EXISTS TILE_FEATURE_MAPPING (
  TILE_ID STRING,
  AGGREGATION_ID STRING,
  FEATURE_NAME STRING,
  FEATURE_TYPE STRING,
  FEATURE_VERSION STRING,
  FEATURE_READINESS STRING,
  FEATURE_EVENT_DATA_IDS STRING,
  IS_DELETED BOOLEAN,
  CREATED_AT TIMESTAMP
) USING DELTA PARTITIONED BY (TILE_ID);
