# Any PR must that integrates with the main branch MUST add one changelog entry
# If a changelog entry is not required, either do one of the following
#   - Add 'Skip Changelog' label to the PR
#   - Add 'dependencies' label to PR
#   - PR title contains text '[chore]'

name: changelog
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'Skip Changelog') && !contains(github.event.pull_request.title, '[chore]')}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ensure changes to the CHANGELOG
        run: |
          if [[ $(git diff --name-only $(git merge-base origin/main ${{ github.event.pull_request.head.sha }}) ${{ github.event.pull_request.head.sha }} ./CHANGELOG.md) ]]; then
            echo "The CHANGELOG.md was modified."
          else
            echo "The CHANGELOG.md was not modified."
            echo "See CONTRIBUTING.md for more details"
            echo "Alternately, add either \"[chore]\" to the title of the pull request or add the \"Skip Changelog\" label if this job should be skipped."
            exit 1
          fi
