# This workflow will check to see what diffs will be made to the documentation.
# If there are any, this will fail the check. This is to ensure that all changes that are being made to
# documentation are signed off by a developer.
#
# To sign off, or skip the documentation check, add:
# - Add 'Documentation Changes Confirmed' label to the PR

name: documentation
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build-updated-docs:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'documentation') }}
    strategy:
      matrix:
        python-version:
          - 3.10.14
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Checkout branch
        run: git checkout "origin/${{ github.head_ref }}"
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install packages needed for build
        run: |-
          sudo apt-get update
          sudo apt-get install libkrb5-dev libsasl2-dev libpython3-dev g++ gcc
      - name: Install wkhtmltopdf
        run: |-
          sudo apt-get update
          sudo apt-get install wkhtmltopdf
      - name: Building docs for current branch
        run: task docs-persist-reference
      - name: Cache updated docs
        run: |-
          mkdir docs-updated
          mv site/reference/* docs-updated/
          rm -rf site/
      - name: Checkout merge base
        run: git checkout --force $(git merge-base "origin/${{ github.head_ref }}" origin/main)
      - name: Building docs for base branch
        run: task docs-persist-reference
      - name: Cache base docs
        run: |-
          mkdir docs-base
          mv site/reference/* docs-base/
          rm -rf site/
      - name: Install diff2html
        run: npm install -g diff2html-cli
      - name: Diff docs
        continue-on-error: true
        run: diff --new-file -ur docs-base/ docs-updated/ > diff.txt
      - name: Generate HTML
        run: cat diff.txt | diff2html -i stdin --title="Documentation Differences" -F diff.html --style="side" --renderNothingWhenEmpty
      - name: Upload diff html
        uses: actions/upload-artifact@v4.5.0
        with:
          name: docs-diff.html
          path: diff.html
      - name: Fail if diff is not empty
        run: |-
          if [ -s diff.txt ]; then
            cat diff.txt
            echo "Documentation changes detected. Please confirm that these changes are expected."
            exit 1;
          fi
