name: notify
'on':
  pull_request:
    types:
    - closed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  slack:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'breaking') }}
    steps:
    - uses: actions/checkout@v4
    - env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_OAUTH }}
      name: Send Slack notification to user-experience channel
      uses: slackapi/slack-github-action@v2.1.0
      with:
        method: chat.postMessage
        token: ${{ secrets.SLACK_OAUTH }}
        payload: |
          channel: C042PLEC8D9
          text: "${{ github.event.repository.name }} Breaking changes -- ${{ github.event.pull_request.title }} [#${{ github.event.number }}]"
          blocks:
            - type: section
              text:
                type: mrkdwn
                text: "`${{ github.event.repository.name }}` Breaking changes -- ${{ github.event.pull_request.title }} [#${{ github.event.number }}]"
            - type: section
              text:
                type: mrkdwn
                text: "Actor: ${{ github.actor }}"
            - type: section
              text:
                type: mrkdwn
                text: "Changes: ${{ github.event.pull_request._links.html.href }}/files"
